class WFPlasmaMedia extends WFMeshImports;

// orbital particle mesh
#exec MESH IMPORT MESH=Orbit1 ANIVFILE=MODELS\Orbit1_a.3d DATAFILE=MODELS\Orbit1_d.3d X=0 Y=0 Z=0
#exec MESH ORIGIN MESH=Orbit1 X=0 Y=0 Z=0

#exec MESH SEQUENCE MESH=Orbit1 SEQ=All  STARTFRAME=0 NUMFRAMES=81
#exec MESH SEQUENCE MESH=Orbit1 SEQ=orb1 STARTFRAME=0 NUMFRAMES=81

// orbital particle mesh
#exec MESH IMPORT MESH=Orbit2 ANIVFILE=MODELS\Orbit2_a.3d DATAFILE=MODELS\Orbit2_d.3d X=0 Y=0 Z=0
#exec MESH ORIGIN MESH=Orbit2 X=0 Y=0 Z=0

#exec MESH SEQUENCE MESH=Orbit2 SEQ=All  STARTFRAME=0 NUMFRAMES=81
#exec MESH SEQUENCE MESH=Orbit2 SEQ=orb2 STARTFRAME=0 NUMFRAMES=81

// orbital particle mesh
#exec MESH IMPORT MESH=Orbit3 ANIVFILE=MODELS\Orbit3_a.3d DATAFILE=MODELS\Orbit3_d.3d X=0 Y=0 Z=0
#exec MESH ORIGIN MESH=Orbit3 X=0 Y=0 Z=0

#exec MESH SEQUENCE MESH=Orbit3 SEQ=All  STARTFRAME=0 NUMFRAMES=81
#exec MESH SEQUENCE MESH=Orbit3 SEQ=orb3 STARTFRAME=0 NUMFRAMES=81

// plasma core
#exec MESH IMPORT MESH=WFPlasmaCore ANIVFILE=MODELS\PlasmaCore_a.3d DATAFILE=MODELS\PlasmaCore_d.3d X=0 Y=0 Z=0
#exec MESH ORIGIN MESH=WFPlasmaCore X=0 Y=0 Z=0

#exec MESH SEQUENCE MESH=WFPlasmaCore SEQ=All  STARTFRAME=0 NUMFRAMES=1
#exec MESH SEQUENCE MESH=WFPlasmaCore SEQ=core STARTFRAME=0 NUMFRAMES=1

#exec MESHMAP NEW   MESHMAP=WFPlasmaCore MESH=WFPlasmaCore
#exec MESHMAP SCALE MESHMAP=WFPlasmaCore X=0.1 Y=0.1 Z=0.2

// ambient sound
#exec AUDIO IMPORT FILE="Sounds\plasma2.Wav" NAME=WFPlasmaAmb


